import sys
import os
import time
import argparse
import random
import math
import glob
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.amp import autocast, GradScaler
from torch.utils.data import DataLoader, Dataset
from pathlib import Path

def is_rank0():
    # Simple script doesn't use DDP yet, so rank is always 0
    return True

def set_mae_p(model, p):
    for m in model.modules():
        if hasattr(m, 'p_min') and hasattr(m, 'p_max') and not isinstance(m, Encoder):
            # This targets the MAEReplacer inside the encoder
            m.p_min = float(p)
            m.p_max = float(p)

def tstats(name, x):
    if x is None:
        print(f"{name}: None")
        return
    if isinstance(x, np.ndarray):
        x = torch.from_numpy(x)
    if not torch.is_tensor(x):
        print(f"{name}: type={type(x)}")
        return
    xd = x.detach()
    finite = torch.isfinite(xd)
    fin_ratio = finite.float().mean().item()
    if fin_ratio < 1.0:
        xd = xd[finite]
    if xd.numel() == 0:
        print(f"{name}: all non-finite")
        return
    print(
        f"{name}: shape={tuple(x.shape)} dtype={x.dtype} dev={x.device} "
        f"min={xd.min().item():+.4f} max={xd.max().item():+.4f} "
        f"mean={xd.mean().item():+.4f} std={xd.std(unbiased=False).item():+.4f} "
        f"finite={fin_ratio*100:.1f}%"
    )


# Add parent directory to path to pick up dreamer4 package
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

try:
    from dreamer4.model import Dynamics, Encoder, Tokenizer, pack_bottleneck_to_spatial, temporal_patchify, temporal_unpatchify
    from dreamer4.train_dynamics import (
        dynamics_pretrain_loss, 
        load_frozen_tokenizer_from_pt_ckpt,
        run_dynamics_eval,
        make_tau_schedule,
        decode_packed_to_frames,
        log_dynamics_eval_wandb
    )
    from dreamer4.viz_utils import save_dynamics_eval
    import dreamer4.train_dynamics
    import wandb
except ImportError:
    sys.path.append(os.getcwd())
    from dreamer4.model import Dynamics, Encoder, Tokenizer, pack_bottleneck_to_spatial, temporal_patchify, temporal_unpatchify
    from dreamer4.train_dynamics import (
        dynamics_pretrain_loss, 
        load_frozen_tokenizer_from_pt_ckpt,
        run_dynamics_eval,
        make_tau_schedule,
        decode_packed_to_frames,
        log_dynamics_eval_wandb
    )
    from dreamer4.viz_utils import save_dynamics_eval
    import dreamer4.train_dynamics
    import wandb

try:
    from dreamer4.activation_monitor import ActivationMonitor
except ImportError:
    ActivationMonitor = None

def save_ckpt(path: Path, *, step: int, dyn_model, opt, scaler, args: argparse.Namespace):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    obj = {
        "step": step,
        "dynamics": (dyn_model.module.state_dict() if hasattr(dyn_model, "module") else dyn_model.state_dict()),
        "opt": opt.state_dict(),
        "scaler": scaler.state_dict() if scaler is not None else None,
        "args": vars(args),
    }
    tmp = path.with_suffix(".tmp")
    torch.save(obj, tmp)
    tmp.replace(path)

def load_ckpt(path: Path, *, dyn_model, opt, scaler) -> int:
    path = Path(path)
    if not path.exists():
        return 0
    ckpt = torch.load(path, map_location="cpu")
    state = ckpt["dynamics"]
    (dyn_model.module if hasattr(dyn_model, "module") else dyn_model).load_state_dict(state, strict=True)
    if opt is not None and "opt" in ckpt:
        opt.load_state_dict(ckpt["opt"])
    if scaler is not None and ckpt.get("scaler") is not None:
        scaler.load_state_dict(ckpt["scaler"])
    return int(ckpt.get("step", 0))

def seed_everything(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

class PushTShardedDataset(Dataset):
    """
    Custom dataset for PushT shards generated by generate_pusht_dataset.py.
    Each shard contains: frames, actions, rewards, is_terminal, is_first.
    """
    def __init__(self, outdirs, seq_len=16):
        self.seq_len = seq_len
        self.outdirs = [outdirs] if isinstance(outdirs, str) else outdirs
        self.shards = []
        
        # Discover shards
        for d in self.outdirs:
            # Assuming structure: data_dir/pusht/*.pt or data_dir/*.pt
            # generate_pusht_dataset.py outputs to out_dir/pusht/shard_XXXX.pt
            # User passes out_dir usually.
            search_paths = [
                os.path.join(d, "pusht", "*.pt"),
                os.path.join(d, "*.pt")
            ]
            for p in search_paths:
                found = sorted(glob.glob(p))
                if found:
                    self.shards.extend(found)
                    break
        
        if not self.shards:
            print(f"Warning: No shards found in {self.outdirs}")

        self.index = []
        self.cache = {} # Simple cache
        
        # Build index (shard_idx, start_idx)
        # To avoid loading all shards to count frames, we assume they are valid or load lazily.
        # But for __len__ we need counts.
        # Let's verify a few or trust generate script produced good shards.
        # For speed, let's just load them if count is small (<100).
        
        print(f"Indexing {len(self.shards)} shards...")
        for shard_idx, p in enumerate(self.shards):
            try:
                # We need to know length. 
                # Optimization: save metadata in filename or separate file?
                # or just load header? torch.load loads whole file typically.
                # For now load it.
                data = torch.load(p, map_location="cpu")
                N = data["frames"].shape[0]
                if N > seq_len:
                    # We can start from 0 to N - seq_len
                    # We accept overlapping windows? Yes.
                    num_starts = N - seq_len
                    for i in range(num_starts):
                        self.index.append((shard_idx, i))
                        
                # Cache small number of shards in memory if possible?
                # Only if memory allows. Let's not cache eagerly.
            except Exception as e:
                print(f"Error loading shard {p}: {e}")
        
        print(f"dataset len: {len(self.index)}")

    def get_source_counts(self):
        counts = {}
        for shard_idx, _ in self.index:
            path = self.shards[shard_idx]
            # Assumes path like .../source/shard_XXXX.pt or .../source/pusht/shard_XXXX.pt
            # We want the folder name that distinguish train vs play
            parts = path.split(os.sep)
            # If path is data/pusht_train/pusht/shard_0000.pt, parts[-3] is pusht_train
            if "pusht" in parts[-2]:
                source = parts[-3]
            else:
                source = parts[-2]
            counts[source] = counts.get(source, 0) + 1
        return counts

    def __len__(self):
        return len(self.index)
    
    def __getitem__(self, idx):
        shard_idx, start = self.index[idx]
        path = self.shards[shard_idx]
        
        # Load shard (cached?)
        if path in self.cache:
            data = self.cache[path]
        else:
            data = torch.load(path, map_location="cpu")
            # Simple LRU or just cache all if small dataset (PushT is small)
            if len(self.cache) < 20: 
                self.cache[path] = data
        
        # Get window
        end = start + self.seq_len # returns T frames
        # Usually dynamics needs T+1 frames? 
        # dynamics_pretrain_loss takes z1 (targets).
        # We usually predict next latent.
        # If we have T frames, we can self-supervise T-1 transitions?
        # dreamer4 usually takes sequence of length T.
        
        frames = data["frames"][start:end].float() / 255.0 # (T, 3, H, W)
        actions = data["actions"][start:end].float() # (T, A)
        rewards = data["rewards"][start:end].float() # (T)
        
        # Handle Act Mask? PushT doesn't have it, assume all 1s
        act_mask = torch.ones_like(actions) 
        
        return {
            "frames": frames,
            "actions": actions,
            "rewards": rewards,
            "act_mask": act_mask
        }

def main():
    parser = argparse.ArgumentParser()
    default_data_dir = os.path.join(os.path.dirname(__file__), "../data/pusht_train")
    parser.add_argument("--data_dirs", type=str, nargs="+", default=[default_data_dir])
    parser.add_argument("--tokenizer_ckpt", type=str, default="tok_latest.pt")
    parser.add_argument("--seq_len", type=int, default=16)
    parser.add_argument("--max_steps", type=int, default=1000000)
    parser.add_argument("--batch_size", type=int, default=8)
    parser.add_argument("--ckpt_dir", type=str, default=".")
    parser.add_argument("--verbose", action="store_true")
    
    # Dynamics Config
    parser.add_argument("--d_model_dyn", type=int, default=256)
    parser.add_argument("--dyn_depth", type=int, default=4)
    parser.add_argument("--n_heads", type=int, default=4)
    parser.add_argument("--k_max", type=int, default=16)
    parser.add_argument("--packing_factor", type=int, default=1)
    parser.add_argument("--dropout", type=float, default=0.0)
    parser.add_argument("--mlp_ratio", type=float, default=4.0)
    parser.add_argument("--time_every", type=int, default=4)
    parser.add_argument("--space_mode", type=str, default="wm_agent_isolated")
    parser.add_argument("--n_register", type=int, default=0)
    parser.add_argument("--n_agent", type=int, default=0)
    
    # Training args
    parser.add_argument("--lr", type=float, default=3e-4) # Unified default
    parser.add_argument("--weight_decay", type=float, default=1e-2)
    parser.add_argument("--num_workers", type=int, default=4)
    parser.add_argument("--grad_accum", type=int, default=1)
    parser.add_argument("--grad_clip", type=float, default=1.0)
    parser.add_argument("--save_every", type=int, default=10000)
    parser.add_argument("--force_retrain", action="store_true")
    parser.add_argument("--action_dim", type=int, default=2)
    
    # Shortcut / self-supervision
    parser.add_argument("--bootstrap_start", type=int, default=1000)
    parser.add_argument("--self_fraction", type=float, default=0.25)

    # Wandb
    parser.add_argument("--wandb_project", type=str, default=None)
    parser.add_argument("--wandb_run_name", type=str, default=None)
    parser.add_argument("--wandb_entity", type=str, default=None)
    parser.add_argument("--no_wandb", action="store_true")

    parser.add_argument("--log_every", type=int, default=1000)
    parser.add_argument("--monitor_every", type=int, default=10000) # Re-added for viz
    parser.add_argument("--monitor_activations", action="store_true")
    parser.add_argument("--compile", action="store_true")
    
    # Eval / Viz
    parser.add_argument("--eval_every", type=int, default=50000)
    parser.add_argument("--eval_batch_size", type=int, default=4)
    parser.add_argument("--eval_max_items", type=int, default=4)
    parser.add_argument("--eval_ctx", type=int, default=4)
    parser.add_argument("--eval_horizon", type=int, default=12)
    parser.add_argument("--eval_schedule", type=str, default="finest", choices=["finest", "shortcut"])
    parser.add_argument("--eval_d", type=float, default=0.25)
    parser.add_argument("--eval_mask_ratio", type=float, default=0.3)

    args = parser.parse_args()

    # Save path
    if not os.path.exists(args.ckpt_dir):
        os.makedirs(args.ckpt_dir, exist_ok=True)
        
    save_path = os.path.join(args.ckpt_dir, "dynamics_pusht.pt")
    if os.path.exists(save_path) and not args.force_retrain:
        print(f"Model already trained at {save_path}. Use --force_retrain to override.")
        return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    
    seed_everything(random.randint(1, 1000000))

    # Wandb Init
    if (args.wandb_project) and not args.no_wandb:
        wandb.init(
            project=args.wandb_project,
            name=args.wandb_run_name or "dynamics_overfit",
            config=vars(args),
            mode="offline"
        )
    elif wandb.run is None:
        # Mock wandb.log to avoid errors in run_dynamics_eval if wandb not used
        wandb.log = lambda *args, **kwargs: None

    # Monkeypatch log_dynamics_eval_wandb to save locally
    original_log_dynamics_eval_wandb = dreamer4.train_dynamics.log_dynamics_eval_wandb
    
    def chained_log_dynamics_eval_wandb(**kwargs):
        # Call original if wandb is active
        if wandb.run is not None:
             original_log_dynamics_eval_wandb(**kwargs)
        
        # Save locally
        save_dir = os.path.join(args.ckpt_dir, "viz_eval")
        save_dynamics_eval(
            gt=kwargs['gt'],
            pred=kwargs['pred'],
            ctx_length=kwargs['ctx_length'],
            step=kwargs['step'],
            save_dir=save_dir,
            tag=kwargs.get('tag', 'eval'),
            max_items=kwargs.get('max_items', 4)
        )

    dreamer4.train_dynamics.log_dynamics_eval_wandb = chained_log_dynamics_eval_wandb

    # Load Tokenizer
    abs_tok_path = os.path.abspath(args.tokenizer_ckpt)
    print(f"Loading tokenizer from {abs_tok_path}...")
    enc, dec, tok_args = load_frozen_tokenizer_from_pt_ckpt(args.tokenizer_ckpt, device=device)
    
    # Wrap in Tokenizer (important for consistent forward path)
    tok = Tokenizer(enc, dec).to(device).eval()
    
    # Ensure no masking during dynamics training
    set_mae_p(tok.encoder, 0.0)

    patch = int(tok_args.get("patch", 4))
    d_bottleneck = int(tok_args.get("d_bottleneck", 32))
    n_latents = int(tok_args.get("n_latents", 16))
    H_img = int(tok_args.get("H", 128))
    W_img = int(tok_args.get("W", 128))
    
    print("tok_args:", tok_args)
    assert "H" in tok_args and "W" in tok_args and "patch" in tok_args, "Tokenizer ckpt missing args; load function likely not parsing your checkpoint."
    assert (H_img % patch) == 0 and (W_img % patch) == 0
    print("Loaded tokenizer:", "H,W,patch=", H_img, W_img, patch, "d_bottleneck=", d_bottleneck, "n_latents=", n_latents)
    
    n_spatial = n_latents // args.packing_factor
    d_spatial = d_bottleneck * args.packing_factor

    # Load Data
    print(f"Initializing PushTDataset from {args.data_dirs}...")
    valid_dirs = [d for d in args.data_dirs if os.path.exists(d)]
    dataset = PushTShardedDataset(
        outdirs=valid_dirs if valid_dirs else args.data_dirs,
        seq_len=args.seq_len
    )
    
    dataloader = DataLoader(
        dataset, 
        batch_size=args.batch_size, 
        shuffle=True, 
        num_workers=args.num_workers,
        pin_memory=True,
        drop_last=True
    )
    
    # Data Distribution Logging
    if is_rank0():
        counts = dataset.get_source_counts()
        print("\nData distribution by source (windows):")
        for src, count in counts.items():
            print(f"  {src}: {count} windows")
        print(f"Total windows: {len(dataset)}\n")

    # Dynamics Model

    print("Initializing Dynamics...")
    dyn = Dynamics(
        d_model=args.d_model_dyn,
        d_bottleneck=d_bottleneck,
        d_spatial=d_spatial,
        n_spatial=n_spatial,
        n_register=args.n_register,
        n_agent=args.n_agent,
        n_heads=args.n_heads,
        depth=args.dyn_depth,
        k_max=args.k_max,
        dropout=args.dropout,
        mlp_ratio=args.mlp_ratio,
        time_every=args.time_every,
        space_mode=args.space_mode,
        action_dim=args.action_dim
    ).to(device)
    
    if args.compile:
        dyn = torch.compile(dyn)
        
    optimizer = optim.AdamW(dyn.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    use_amp = torch.cuda.is_available()

    use_amp = (device.type == "cuda")
    scaler = GradScaler(enabled=use_amp)
    
    if ActivationMonitor is not None:
         monitor = ActivationMonitor(dyn, log_every=args.monitor_every, active=args.monitor_activations)
    else:
         monitor = None

    print("Starting Training...")
    step = 0
    t0 = time.time()
    grad_accum = max(1, int(args.grad_accum))
    
    dyn.train()
    
    # Resume
    if args.ckpt_dir:
        resume_path = os.path.join(args.ckpt_dir, "dynamics_pusht.pt")
        if os.path.exists(resume_path) and not args.force_retrain: # force_retrain handled earlier but good check
             pass # Use explicit resume arg if needed or auto-resume? 
             # The standard script uses --resume. I haven't added --resume arg. 
             # But I see save_ckpt saves to "latest.pt".
             # Let's keep it simple: if latest.pt exists, load it?
             # My arg parser says:
             # if os.path.exists(save_path) and not args.force_retrain: return
             # This means it aborts if trained!
             # So resuming happens if I remove that check or handle it differently.
             # The user asked for "overfit" scripts originally, which were "run once".
             # But now we want a full training script.
             # I should probably remove the "abort if exists" check earlier if I want to support resume.
             # For now, let's just stick to "start fresh".
             pass
             
    # Initial Tokenizer Reconstruction Baseline Check
    print("Running initial tokenizer reconstruction baseline check...")
    with torch.no_grad():
        batch = next(iter(dataloader))
        # Use T=8 to exactly match the sequence length used during tokenizer training
        T_baseline = 8 
        frames_baseline = batch['frames'][:4, :T_baseline].to(device)
        if frames_baseline.dtype == torch.uint8:
            frames_baseline = frames_baseline.float() / 255.0
        assert H_img == frames_baseline.shape[-2] and W_img == frames_baseline.shape[-1], (H_img, W_img, frames_baseline.shape)
        patches_baseline = temporal_patchify(frames_baseline, patch)

        enc.eval(); dec.eval()
        
        # DEBUG
        with torch.no_grad():
            for p_test in [0.0, 0.9]:
                set_mae_p(enc, p_test)
                z, (mask, _) = enc(patches_baseline)
                recon = dec(z)

                print(
                    f"p={p_test}  "
                    f"mask.mean={mask.float().mean().item():.3f}  "
                    f"z.std={z.float().std().item():.3f}  "
                    f"recon.range=[{recon.min().item():.3f}, {recon.max().item():.3f}]"
                )
        # DEBUG
        # DEBUG
        # tok = Tokenizer(enc, dec) is already defined at line 304 and used below

        
        save_dir_baseline = os.path.join(args.ckpt_dir, "viz_baseline")
        os.makedirs(save_dir_baseline, exist_ok=True)

        for p_test in [0.0, 0.75, 0.9, 0.95]:
            # Temporarily set MAE probability on encoder
            set_mae_p(enc, p_test)
            
            with torch.no_grad():
                pred, mae_mask, keep_prob = tok(patches_baseline)
                recon_full = temporal_unpatchify(pred, H_img, W_img, 3, patch).clamp(0, 1)
            # Save
            tag_suffix = f"MASK_{int(p_test*100):02d}"
            save_dynamics_eval(
                gt=frames_baseline,
                pred=recon_full,
                ctx_length=T_baseline,
                step=0,
                save_dir=save_dir_baseline,
                tag=f"tokenizer_FULL_{tag_suffix}",
                max_items=4
            )
            print(f"  Processed p={p_test} -> Saved FULL and LEAKED viz")

        # Reset to 0% for actual dynamics training
        set_mae_p(enc, 0.0)
        print(f"Baseline check complete. Folders: {save_dir_baseline}")
        print("NOTE: 'FULL_MASK_90' should match Row 4 of your training viz.")
        print("NOTE: 'LEAKED_MASK_90' should match Row 3 of your training viz.")

        # SANITY CHECK: Compare Raw Encoder vs Tokenizer Output
        print("Running RAW vs TOKENIZER comparison check...")
        set_mae_p(tok.encoder, 0.0)
        with torch.no_grad():
            # Raw Enc -> Dec
            z_raw, _ = enc(patches_baseline)
            recon_raw = temporal_unpatchify(dec(z_raw), H_img, W_img, 3, patch).clamp(0, 1)
            
            # Tokenizer -> Dec
            pred_tok, _, _, _ = tok(patches_baseline, return_z=True)
            recon_tok = temporal_unpatchify(pred_tok, H_img, W_img, 3, patch).clamp(0, 1)
            
            mse_diff = (recon_raw - recon_tok).pow(2).mean().item()
            mse_raw_gt = (recon_raw - frames_baseline).pow(2).mean().item()
            mse_tok_gt = (recon_tok - frames_baseline).pow(2).mean().item()
            
            print(f"  Raw vs Tok MSE diff: {mse_diff:.8f}")
            print(f"  Raw vs GT MSE:       {mse_raw_gt:.8f}")
            print(f"  Tok vs GT MSE:       {mse_tok_gt:.8f}")
            
            if mse_diff > 1e-6:
                print("  WARNING: Raw encoder path differs from Tokenizer path! Using Tokenizer path is safer.")
            else:
                print("  SUCCESS: Raw and Tokenizer paths are identical (as expected with mae_p=0).")
            
            # Reset MAE used for check
            set_mae_p(tok.encoder, 0.0)



    while step < args.max_steps:
        for batch in dataloader:
            if step >= args.max_steps:
                break
            
            frames = batch['frames'].to(device, non_blocking=True)
            actions = batch['actions'].to(device, non_blocking=True)
            rewards = batch['rewards'].to(device, non_blocking=True)
            act_mask = batch['act_mask'].to(device, non_blocking=True)
            
            # --- NORMALIZE ACTIONS TO [-1, 1] ---
            # PushT demos use pixel coordinates (~0..512)
            # ActionEncoder expects [-1,1]
            actions = (actions / 256.0) - 1.0
            actions = actions.clamp(-1, 1)

            if step % 200 == 0 and args.verbose:
                print(f"actions_norm range: [{actions.min().item():.3f}, {actions.max().item():.3f}] "
                    f"mean={actions.mean().item():.3f} std={actions.std(unbiased=False).item():.3f}")


            if frames.dtype == torch.uint8:
                frames = frames.float() / 255.0


            if step % 200 == 0 and args.verbose:
                print("\n=== BATCH SANITY ===")
                tstats("frames", frames)
                tstats("actions_raw", actions)
                tstats("rewards_raw", rewards)
                tstats("act_mask", act_mask)

                # Quick guess: are actions pixels [0,512] or normalized [-1,1]?
                a_min = actions.detach().min().item()
                a_max = actions.detach().max().item()
                if a_min >= 0.0 and a_max > 2.0:
                    print("NOTE: actions look UNNORMALIZED (likely pixel coords). Consider normalizing to [-1,1].")
                elif a_min >= -1.2 and a_max <= 1.2:
                    print("NOTE: actions look normalized to ~[-1,1].")
                else:
                    print("NOTE: actions have unusual range; verify ActionEncoder expectation.")



            # Causal Shift:
            # frames[t] is s_t.
            # act[t] is action taken at s_t (leads to s_{t+1}).
            # Model at step t (predicting s_t) should see a_{t-1}.
            # So we shift actions right by 1, and same for rewards.
            actions_shifted = torch.zeros_like(actions)
            actions_shifted[:, 1:] = actions[:, :-1]
            actions = actions_shifted
            
            rewards_shifted = torch.zeros_like(rewards)
            rewards_shifted[:, 1:] = rewards[:, :-1]
            rewards = rewards_shifted

            # Encode with frozen tokenizer
            with torch.no_grad():
                patches = temporal_patchify(frames, patch)


                if step % 500 == 0 and args.verbose:
                    print("\n=== TOKENIZER ROUNDTRIP ===")
                    with torch.no_grad():
                        # Encode
                        z_btLd, (mae_mask, keep_prob) = tok.encoder(patches)
                        tstats("mae_mask.mean", mae_mask.float().mean())
                        tstats("keep_prob", keep_prob)
                        tstats("z_btLd", z_btLd)

                        # Decode
                        recon_patches = dec(z_btLd)
                        recon_frames = temporal_unpatchify(recon_patches, H_img, W_img, 3, patch).clamp(0,1)

                        # Metrics
                        mse = (recon_frames - frames).float().pow(2).mean().item()
                        mae = (recon_frames - frames).float().abs().mean().item()
                        print(f"recon mse={mse:.6f}  mae={mae:.6f}")

                        # Range sanity
                        tstats("recon_frames", recon_frames)

                # Use Tokenizer to extract latents consistently. 
                # This ensures we get exactly what the decoder expects.
                # _, _, _, z_btLd = tok(patches, return_z=True)
                z_btLd, _ = tok.encoder(patches)


                if step % 500 == 0 and args.verbose:
                    print("\n=== LATENT STABILITY ===")
                    with torch.no_grad():
                        # z_btLd: (B,T,L,D)
                        dz = (z_btLd[:, 1:] - z_btLd[:, :-1]).float()
                        per_t = dz.pow(2).mean(dim=(0,2,3))  # (T-1,)
                        print("mean dz^2 per timestep:", [float(x) for x in per_t.cpu()])
                        print("overall dz^2:", float(dz.pow(2).mean().cpu()))

                z1 = pack_bottleneck_to_spatial(z_btLd, n_spatial=n_spatial, k=args.packing_factor)


            if step % 1000 == 0:
                print("\n=== ACTION SENSITIVITY ===")
                with torch.no_grad():
                    # real
                    loss_real, _ = dynamics_pretrain_loss(
                        dyn, z1=z1, actions=actions, rewards=rewards, act_mask=act_mask,
                        k_max=args.k_max, B_self=0, step=step, bootstrap_start=1000
                    )

                    # zeroed actions
                    actions_zero = torch.zeros_like(actions)
                    loss_zero, _ = dynamics_pretrain_loss(
                        dyn, z1=z1, actions=actions_zero, rewards=rewards, act_mask=act_mask,
                        k_max=args.k_max, B_self=0, step=step, bootstrap_start=1000
                    )

                    # permuted batch actions
                    perm = torch.randperm(actions.shape[0], device=actions.device)
                    loss_perm, _ = dynamics_pretrain_loss(
                        dyn, z1=z1, actions=actions[perm], rewards=rewards, act_mask=act_mask,
                        k_max=args.k_max, B_self=0, step=step, bootstrap_start=1000
                    )

                    print(f"loss_real={loss_real.item():.9f}  loss_zero={loss_zero.item():.9f}  loss_perm={loss_perm.item():.9f}")

            if step % 1000 == 0:
                print("\n=== ACTION EFFECT PROBE ===")
                with torch.no_grad():
                    B, T = z1.shape[:2]

                    # Use a fixed corruption so comparisons are meaningful
                    step_idxs = torch.full((B, T), int(round(math.log2(args.k_max))), device=z1.device, dtype=torch.long)  # emax (finest)
                    signal_idxs = torch.full((B, T), args.k_max - 1, device=z1.device, dtype=torch.long)                  # near-clean

                    # Build a fixed z_tilde (use the same noise for all variants)
                    sigma = torch.full((B, T), 0.5, device=z1.device, dtype=z1.dtype)  # fixed corruption strength
                    z0 = torch.randn_like(z1)
                    z_tilde = (1.0 - sigma)[..., None, None] * z0 + sigma[..., None, None] * z1

                    # Variant actions
                    a_real = actions
                    a_zero = torch.zeros_like(actions)
                    perm = torch.randperm(B, device=z1.device)
                    a_perm = actions[perm]

                    # Forward
                    y_real, _, _ = dyn(a_real, step_idxs, signal_idxs, z_tilde, act_mask=act_mask)
                    y_zero, _, _ = dyn(a_zero, step_idxs, signal_idxs, z_tilde, act_mask=act_mask)
                    y_perm, _, _ = dyn(a_perm, step_idxs, signal_idxs, z_tilde, act_mask=act_mask)

                    # Measure effect sizes
                    d_rz = (y_real - y_zero).float().pow(2).mean().sqrt().item()
                    d_rp = (y_real - y_perm).float().pow(2).mean().sqrt().item()
                    y_std = y_real.float().std(unbiased=False).item()

                    print(f"||y_real - y_zero||_rms = {d_rz:.6e}")
                    print(f"||y_real - y_perm||_rms = {d_rp:.6e}")
                    print(f"std(y_real)            = {y_std:.6e}")

                    def probe(actions_in, tag):
                        y_real, _, _ = dyn(actions_in, step_idxs, signal_idxs, z_tilde, act_mask=act_mask)
                        y_zero, _, _ = dyn(torch.zeros_like(actions_in), step_idxs, signal_idxs, z_tilde, act_mask=act_mask)
                        d = (y_real - y_zero).float().pow(2).mean().sqrt().item()
                        print(f"[{tag}] ||y_real - y_zero||_rms = {d:.6e}")

                    # (build step_idxs, signal_idxs, sigma, z0, z_tilde exactly like your current probe)
                    # probe(actions_raw,  "NO_SHIFT")
                    # probe(actions_shifted, "SHIFTED")


                    # for sigma_val in [0.1, 0.3, 0.5, 0.8]:
                    #     sigma = torch.full((B, T), sigma_val, device=z1.device, dtype=z1.dtype)
                    #     z0 = torch.randn_like(z1)
                    #     z_tilde = (1.0 - sigma)[..., None, None] * z0 + sigma[..., None, None] * z1

                    #     y_real, _, _ = dyn(actions, step_idxs, signal_idxs, z_tilde, act_mask=act_mask)
                    #     y_zero, _, _ = dyn(torch.zeros_like(actions), step_idxs, signal_idxs, z_tilde, act_mask=act_mask)

                    #     d = (y_real - y_zero).float().pow(2).mean().sqrt().item()
                    #     print(f"sigma={sigma_val:.1f}  ||y_real - y_zero|| = {d:.6e}")


            # Train step
            if (step + 1) % grad_accum == 0:
                optimizer.zero_grad(set_to_none=True)
                
            if getattr(args, "monitor_activations", False) and monitor is not None:
                # monitor step if strict accumulation
                 if (step + 1) % grad_accum == 0:
                    monitor.step(step)

            B = z1.shape[0]
            B_self = int(round(args.self_fraction * B))
            B_self = max(0, min(B - 1, B_self))

            with autocast(device_type=device.type, enabled=use_amp):
                 loss, aux = dynamics_pretrain_loss(
                    dyn,
                    z1=z1,
                    actions=actions, 
                    rewards=rewards,
                    act_mask=act_mask,
                    k_max=args.k_max,
                    B_self=B_self, 
                    step=step,
                    bootstrap_start=args.bootstrap_start
                )
            
            loss_to_backprop = loss / grad_accum
            scaler.scale(loss_to_backprop).backward()



            do_step = ((step + 1) % grad_accum == 0)
            if do_step:
                # IMPORTANT: unscale before clipping, otherwise clip is meaningless
                scaler.unscale_(optimizer)

                if step % 200 == 0 and args.verbose:
                    print("\n=== GRAD SANITY ===")
                    total_norm = 0.0
                    n = 0
                    for p in dyn.parameters():
                        if p.grad is None:
                            continue
                        g = p.grad.detach()
                        if torch.isfinite(g).all():
                            total_norm += g.float().pow(2).sum().item()
                            n += g.numel()
                    total_norm = math.sqrt(total_norm) if total_norm > 0 else 0.0
                    print(f"grad_l2={total_norm:.6f}  grad_elems={n}")

                # ---- GRAD CLIP HERE ----
                grad_norm = torch.nn.utils.clip_grad_norm_(dyn.parameters(), max_norm=args.grad_clip)

                # optional debug
                if step % 200 == 0:
                    print(f"grad_norm (pre-clip) = {float(grad_norm):.3f}")

                # AMP step
                scaler.step(optimizer)
                scaler.update()

                # clear grads for next accumulation cycle
                optimizer.zero_grad(set_to_none=True)

                if monitor is not None:
                    monitor.log_and_clear(step)
                                
            if step % args.log_every == 0:
                if (args.wandb_project) and not args.no_wandb:
                   log_dict = {"loss": loss.item(), "lr": optimizer.param_groups[0]["lr"]}
                   # Add aux
                   for k, v in aux.items():
                       log_dict[f"aux/{k}"] = v.item() if torch.is_tensor(v) else v
                   wandb.log(log_dict, step=step)
                print(f"Step {step}: Loss = {loss.item():.4f}")
            
            # Visualization
            if args.eval_every > 0 and step % args.eval_every == 0 and step > 0:
                print(f"Running evaluation at step {step}...")
                
                # Setup schedule
                sched = make_tau_schedule(k_max=args.k_max, schedule=args.eval_schedule, d=args.eval_d)
                                
                run_dynamics_eval(
                    encoder=enc,
                    decoder=dec,
                    dyn=dyn,
                    frames=frames,
                    actions=actions if 'actions' in locals() else None,
                    rewards=rewards if 'rewards' in locals() else None,
                    act_mask=act_mask if 'act_mask' in locals() else None,
                    H=H_img, W=W_img, C=3,
                    patch=patch,
                    packing_factor=args.packing_factor,
                    k_max=args.k_max,
                    ctx_length=args.eval_ctx,
                    horizon=args.eval_horizon,
                    sched=sched,
                    max_items=args.eval_max_items,
                    step=step,
                    eval_mask_ratio=args.eval_mask_ratio
                )

            # Checkpointing
            if args.save_every > 0 and (step % args.save_every == 0) and step > 0:
                print(f"Saving checkpoint at step {step}...")
                ckpt_path = os.path.join(args.ckpt_dir, f"dynamics_step_{step:07d}.pt")
                save_ckpt(
                    Path(ckpt_path), 
                    step=step, 
                    dyn_model=dyn, 
                    opt=optimizer, 
                    scaler=scaler, 
                    args=args
                )
                # Also save latest
                latest_path = os.path.join(args.ckpt_dir, "dynamics_latest.pt")
                save_ckpt(
                    Path(latest_path), 
                    step=step, 
                    dyn_model=dyn, 
                    opt=optimizer, 
                    scaler=scaler, 
                    args=args
                )

            step += 1

    print("Saving model...")
    state = {
        "dynamics": dyn.state_dict(),
        "args": vars(args) 
    }
    torch.save(state, save_path)
    print("Done.")

if __name__ == "__main__":
    main()
